import Head from 'next/head'
import Navigation from './Navigation'
import Footer from './Footer'

//import styles from '../styles/Home.module.css'

export default function Layout({ children }) {
    return (
        <div className='paper'>
            <Head>
                <title>MonAmi Patisserie</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation />
            <div className='container container-lg'>
                {children}
            </div>
            <Footer />
        </div>
    )
}
